# Generated by Django 3.2.25 on 2024-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idcursos', models.IntegerField(db_column='idCursos', primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(db_column='Nombre_Curso', max_length=120)),
                ('fechainicial_curso', models.DateTimeField(db_column='FechaInicial_Curso')),
                ('fechafina_cursol', models.DateTimeField(db_column='FechaFina_Cursol')),
                ('link_curso', models.CharField(db_column='Link_Curso', max_length=200)),
                ('descripcion_cursol', models.CharField(db_column='Descripcion_Cursol', max_length=450)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('idhistorial_cambios', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('id_registro_afectado', models.IntegerField()),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_hora_cambio', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_cambios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('idintegrantes', models.AutoField(db_column='idIntegrantes', primary_key=True, serialize=False)),
                ('nombre_integrante', models.CharField(max_length=135)),
                ('semestre', models.CharField(db_column='Semestre', max_length=45)),
                ('correo', models.CharField(db_column='Correo', max_length=90)),
                ('link_git', models.CharField(db_column='Link_Git', max_length=190)),
                ('imagen', models.TextField(db_column='Imagen')),
            ],
            options={
                'db_table': 'integrantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('idnoticia', models.IntegerField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('nombre_noticia', models.CharField(db_column='Nombre_noticia', max_length=600)),
                ('fecha_noticia', models.DateTimeField(db_column='Fecha_noticia')),
                ('link_noticia', models.CharField(db_column='Link_noticia', max_length=250)),
                ('description_noticia', models.CharField(db_column='Description_noticia', max_length=450)),
            ],
            options={
                'db_table': 'noticias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('idproyectos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(db_column='Nombre_Proyecto', max_length=150)),
                ('intengrantes_proyecto', models.CharField(db_column='Intengrantes_Proyecto', max_length=450)),
                ('fecha_proyecto', models.DateTimeField(db_column='Fecha_Proyecto')),
                ('link_proyecto', models.CharField(db_column='Link_Proyecto', max_length=250)),
                ('description_proyecto', models.CharField(db_column='Description_Proyecto', max_length=450)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipo_usuario', models.AutoField(db_column='idTipo_usuario', primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(db_column='Tipo_usuario', max_length=45)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45, unique=True)),
                ('contraseña', models.CharField(db_column='contraseña', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
